from lessons.constants import *
from paw.methods import Url
from . import views

app_name = 'lessons'

urlpatterns = []
url_manager = Url(urlpatterns, views)

url_manager.add_url(EXPRESSION_INDEX, INDEX)
url_manager.add_url(EXPRESSION_INDEX_COURSE_ID, INDEX)
url_manager.add_url(EXPRESSION_COURSES, INDEX)
url_manager.add_url(EXPRESSION_VIEW_LESSON, VIEW_LESSON)
url_manager.add_url(EXPRESSION_DOWNLOAD_FILE, DOWNLOAD_FILE)
url_manager.add_url(EXPRESSION_GENERIC_LESSON_PLANS, GENERIC_LESSON_PLANS)
url_manager.add_url(EXPRESSION_GENERIC_LESSON_PLANS_TOPIC_ID, GENERIC_LESSON_PLANS)
url_manager.add_url(EXPRESSION_DOWNLOAD_ALL_FLASHCARDS, DOWNLOAD_ALL_FLASHCARDS)
url_manager.add_url(EXPRESSION_DOWNLOAD_FLASHCARD, DOWNLOAD_FLASHCARD)
url_manager.add_url(EXPRESSION_DOWNLOAD_ALL, DOWNLOAD_ALL)
url_manager.add_url(EXPRESSION_GENERIC_ACTIVITIES, GENERIC_ACTIVITIES)
url_manager.add_url(EXPRESSION_LESSON_PLANS, LESSON_PLANS)
url_manager.add_url(EXPRESSION_LESSON_PLANS_LESSON_ID, LESSON_PLANS)
url_manager.add_url(EXPRESSION_PRINT_LESSON_PLAN, PRINT_LESSON_PLAN)
url_manager.add_url(EXPRESSION_VIEW_ACTIVITY, VIEW_ACTIVITY)
url_manager.add_url(EXPRESSION_DOWNLOAD_TARGET_LANGUAGE, DOWNLOAD_TARGET_LANGUAGE)
url_manager.add_url(EXPRESSION_DOWNLOAD_ALL_TARGET_LANGUAGES, DOWNLOAD_ALL_TARGET_LANGUAGES)
url_manager.add_url(EXPRESSION_FLASHCARD_MANAGER, FLASHCARD_MANAGER)
url_manager.add_url(EXPRESSION_SEARCH_FLASHCARD, SEARCH_FLASHCARD)
url_manager.add_url(EXPRESSION_GENERATE_FLASHCARD, GENERATE_FLASHCARD)
url_manager.add_url(EXPRESSION_GENERATE_TARGET_LANGUAGE, GENERATE_TARGET_LANGUAGE)

